### ISSUE TITLE
Type-in-text link does not work

### ISSUE THREAD

**Issue by ricklefsv** [olab/Open-Labyrinth#102]
I get the 'Whoops' error when trying to use type-in-text links. I have OLab 3.3.1. Error message is attached
[errorDetails_error56eb95188876d.zip](https://github.com/olab/Open-Labyrinth/files/179126/errorDetails_error56eb95188876d.zip)

**Comment by topps** [comment]
Hi Victor, You are correct. ‘Type-in text’ style links died a while ago and have not really been functional since OLab2.

See http://demo.openlabyrinth.ca/labyrinthManager/global/30 – that method died because we found that nobody was using it.

That approach has been deprecated and replaced by the use of Rules and single line text Questions. See http://demo.openlabyrinth.ca/labyrinthManager/global/57 for an example of how that works.

Note that if you export a copy of Map 57, it will break the Rule which needs to be remapped to the new Question number.

dt

From: ricklefsv
Reply-To: olab/Open-Labyrinth
Date: Friday, March 18, 2016 at 1:55 PM
To: olab/Open-Labyrinth
Subject: [Open-Labyrinth] Type-in-text link does not work (#102)


I get the 'Whoops' error when trying to use type-in-text links. I have OLab 3.3.1. Error message is attached
errorDetails_error56eb95188876d.zip<https://github.com/olab/Open-Labyrinth/files/179126/errorDetails_error56eb95188876d.zip>

**Comment by ricklefsv** [comment]
Thanks a lot for explanation. I will try the rules. But the presence of text-links in Olab is misleading then. Should this feature be removed?
