### ISSUE TITLE
Rules do not work for nodes with titles in Cyrillic

### ISSUE THREAD

**Issue by ricklefsv** [olab/Open-Labyrinth#103]
When creating a rule for nodes with titles in Cyrillic, the browser crashes due to infinite recursion in replaceValue function on line 171 of \www\scripts\rules.js. The closer analysis of the problem revealed the problem in the file \www\application\classes\controller\countermanager.php on lines 283, 298, 326, 341. It has `$word = preg_replace('/[^a-zA-Z0-9_.,; ]/', '', $word);` statement in these lines. Obviously all text in Cyrillic will be replaced to nothing creating a problem. The similar problem will be with languages other than English.

**Comment by topps** [comment]
Thanks for the debugging, Viktor. I will post this in the dev queue for fixing. dt

From: ricklefsv
Reply-To: olab/Open-Labyrinth
Date: Saturday, March 26, 2016 at 6:16 PM
To: olab/Open-Labyrinth
Subject: [Open-Labyrinth] Rules do not work for nodes with titles in Cyrillic (#103)


When creating a rule for nodes with titles in Cyrillic, the browser crashes due to infinite recursion in replaceValue function on line 171 of \www\scripts\rules.js. The closer analysis of the problem revealed the problem in the file \www\application\classes\controller\countermanager.php on lines 283, 298, 326, 341. It has $word = preg_replace('/[^a-zA-Z0-9_.,; ]/', '', $word); statement in these lines. Obviously all text in Cyrillic will be replaced to nothing creating a problem. The similar problem will be with other languages other than English.

**Comment by ricklefsv** [comment]
Thanks for including this issue into dev queue. I have already fixed it in our installation adding it to the language file. I can present you with my solution, but am sure that your programmers’ team will make it better. It would be nice to have the ‘official fix’…

**Comment by sergey-rud** [comment]
@ricklefsv Fixed on the release-candidate branch. Please check and let me know if the problem persists.

**Comment by topps** [comment]
Sergey tells me that this has been fixed. Viktor, would you like to test this out on our demo.olab3 server? ITRex usually uploads such fixes to this demo server right away.

dt

From: ricklefsv
Reply-To: olab/Open-Labyrinth
Date: Saturday, March 26, 2016 at 4:16 AM
To: olab/Open-Labyrinth
Subject: [Open-Labyrinth] Rules do not work for nodes with titles in Cyrillic (#103)


When creating a rule for nodes with titles in Cyrillic, the browser crashes due to infinite recursion in replaceValue function on line 171 of \www\scripts\rules.js. The closer analysis of the problem revealed the problem in the file \www\application\classes\controller\countermanager.php on lines 283, 298, 326, 341. It has $word = preg_replace('/[^a-zA-Z0-9_.,; ]/', '', $word); statement in these lines. Obviously all text in Cyrillic will be replaced to nothing creating a problem. The similar problem will be with other languages other than English.
