### ISSUE TITLE
The installation error with 500 Internal Server Error.

### ISSUE THREAD

**Issue by yusufyilmaz** [olab/Open-Labyrinth#105]
Hi,

The installation process giving 500 error. When I go through the error logs, The issue is related for www/installation/classes/installation.php file on line 205 `if (in_array('mod_rewrite', apache_get_modules())){` somehow apache_get_modules function was not found so I manually returned the condition tru (I know that my apache supports mod_rewrite) and I was able to install the olab. What should you recommend for the concrete solution?

**Comment by sergey-rud** [comment]
Hi, thank you for your report.

Function that checks mod_rewrite available only when PHP installed as Apache module, not CGI. I removed this check, because there is no easy/fast way to check it for CGI. Changes available on the release-candidate branch.

**Comment by topps** [comment]
Thanks for that, Sergey. Makes sense to me. dt

From: Sergey Rud
Reply-To: olab/Open-Labyrinth
Date: Tuesday, May 17, 2016 at 6:13 AM
To: olab/Open-Labyrinth
Subject: Re: [olab/Open-Labyrinth] The installation error with 500 Internal Server Error. (#105)


Hi, thank you for your report.

Function that checks mod_rewrite available only when PHP installed as Apache module, not CGI. I removed this check, because there is no easy/fast way to check it for CGI. Changes available on the release-candidate branch.
