### ISSUE TITLE
Issue with updating from v3.1 to v3.3.2

### ISSUE THREAD

**Issue by a-zharkov** [olab/Open-Labyrinth#113]
Email from Praveen Ramanan

> Alex,
> 
> I got your email address from the github site of openlabyrinth.
> 
> Two years ago, I was able set up our own instance of open labyrinth (v3.1) (WAMP setup). Now there has been a request to upgrade to v 3.3.2  and I ran into issues on upgrading.
> 
> I was following the steps below, but it didn’t work. Do you have any further suggestions  or whether I am missing a step?
> 
> 1)Take a backup of existing OpenLabyrinth ver 3.1 folder under www of our web server directory.
> 2)Download the zip file pertaining to version 3.3.2 or 3.4 from github
> 3)Copy the unzipped folder from Step 2 to our existing WWW openlabyrinth directory except the next folders and files (as given in wiki):
> 
> Folders:
> -www/installation
> -www/application/config (copy only new files, don't replace old one)
> 
> Files:
> -www/install.php
> -www/application/bootstrap.php
> 
> On version 3.1, I didn’t have the installation folder neither the www/install.php. But still I went ahead and copied it.
> 
> 4) Update the database by opening the new openlabyrinth
> http://PATH_TO_NEW_OPENLABYRINTH/updateDatabase
> When I tried step 4, it is taking me to a fresh installation. (which I obviously don’t want) So I skipped it and then tried step 4 again. But I got the default error message that something went wrong.
> 
> Hoping you could help me troubleshoot the issue.
> 
> Regards,
> Praveen

**Comment by sergey-rud** [comment]
We need Praveen’s www/application/logs folder for investigation. Also Apache and MySQL error logs are helpful too.

And please make sure Open-Labyrinth folder is writable: 
 * Run `sudo chown -R apache:apache /var/www/Open-Labyrinth/`. Please note that web server user and group can be 'www-data:www-data' instead of 'apache:apache' or any other. It depends on your configuration, but typically it's 'www-data'.
 * Run `sudo chmod -R 0775 /var/www/Open-Labyrinth/`

**Comment by pramanan** [comment]
serey-rud

When i run http://localhost/OpenLabyrinth/updateDatabase i get a default error page of openlabyrinth. If i right click and view source, i get this 

 <div id="kohana_error" style="display: none">
        <h1><span class="type">Database_Exception [ Deprecated ]:</span> <span class="message">mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead</span></h1>
        <div id="error57fd5babac351" class="content">
            <p><span class="file">MODPATH\database\classes\kohana\database\mysql.php [ 67 ]</span></p>
            <pre class="source"><code><span class="line"><span class="number">62</span> 		catch (Exception $e)
</span><span class="line"><span class="number">63</span> 		{
</span><span class="line"><span class="number">64</span> 			// No connection exists
</span><span class="line"><span class="number">65</span> 			$this-&gt;_connection = NULL;
</span><span class="line"><span class="number">66</span> 
</span><span class="line highlight"><span class="number">67</span> 			throw new Database_Exception(':error',
</span><span class="line"><span class="number">68</span> 				array(':error' =&gt; $e-&gt;getMessage()),
</span><span class="line"><span class="number">69</span> 				$e-&gt;getCode());
</span><span class="line"><span class="number">70</span> 		}
</span><span class="line"><span class="number">71</span> 
</span><span class="line"><span class="number">72</span> 		// \xFF is a better delimiter, but the PHP driver uses underscore

I have attached the full version of that html file. 

I am not seeing any other errors  in either the apache logs or the mysql logs. Also openlabyrinth folder is writable, because i was running the older version in the same folder and i had given permissions as described above before. 
[olaberrorhtml.txt](https://github.com/olab/Open-Labyrinth/files/524599/olaberrorhtml.txt)

**Comment by pramanan** [comment]
I am currently on version 3.1 . Is it ok to just run the update (database) scripts located at OpenLabyrinth\updates starting from 3.1.01 till 3.3.1_5 directly on the mysql database and then deploy the app ?

**Comment by sergey-rud** [comment]
Please try to update OpenLabyrinth as you did before, but replace the file www/application/bootstrap.php too. I have just updated wiki (removed this file from exceptions).

Please feel free to reopen this issue if the problem persists.
Thank you.

**Comment by pramanan** [comment]
sergey-rud

That worked great..The database got updated successfully. I also got this message after running updateDatabase

 OpenLabyrinth
× You have not set a root node, so your labyrinth will not play. Please return to the visual editor, and click on the starting node -> Actions -> Set as Root
Database has been successfully updated.
Go to the home page


However when i try to access

http://localhost/openlabyrinth

On the server The openlabyrinth folder is in 
C:\wamp\www\OpenLabyrinth\

Obviously it thinks the base url for the app is c:\wamp\www instead of c:\wamp\www\openlabyrinth because if i do 
http://localhost/openlabyrinth it gets redirected to http://localhost

Document root on the apache conf file is c:\wamp\www  . (I have other php web projects running successfully on this server.)

Is there a place within the application where i have to set the base URL ? I see that on the code, its using several calls to function URL::base()

**Comment by sergey-rud** [comment]
It's not the best practice to have the same document root for all projects. For OpenLabyrinth it should be: `C:\wamp\www\Open-Labyrinth\www`

However you can change base_url in `www/config.json`

**Comment by pramanan** [comment]
sergey
Thanks. I have modified the document root to be different as suggested by you and updated the config.json. 
Its working now ! Thanks a lot for resolving these issues.

**Comment by sergey-rud** [comment]
You are welcome.

p.s. some details about document root changes - file, which contains Apache's virtual hosts, should have these lines:
1) `<VirtualHost *:80>
        ServerName openlabyrinth.local
        DocumentRoot C:\wamp\www\Open-Labyrinth\www
</VirtualHost>`

when lines were added - we need to restart Apache.
2) then we should add line `127.0.0.1 openlabyrinth.local` to hosts (`C:\Windows\System32\drivers\etc\hosts`):
`127.0.0.1 localhost
127.0.0.1 openlabyrinth.local`
3) base_url should be default - `/`.

After these changes we can see our website using `http://openlabyrinth.local`

Some packages (eg OpenServer, MAMP, etc) - do it for you automatically.

Or, as you already did - just change base_url instead.

**Comment by pramanan** [comment]
Thanks! I will try that and leave the base_url to default to / .
