### ISSUE TITLE
Olab with php5.6

### ISSUE THREAD

**Issue by Iraklis** [olab/Open-Labyrinth#121]
Hey there people! I'm working on a server that had olab3 installed years ago and after an attack, I'm trying to rebuild the whole thing. Unfortunately, my progress is slow, since the installation process is stopped after the app is trying to build the database. The server's OS is an Ubuntu 18.04, so it had php7 installed. I installed php5.6, as well, but the problem persists, just a blank screen after I fill the fields of the database name, etc. The app doesn't output any errors on the console and I can't seem to find any errors, so I'm guessing that olab3.4 is not compatible with php5.6? Maybe the version of MySQL is the problem (currently 5.7.33)? Can anyone confirm any of this or guide me through?

Thanks in advance!

P.S. All the pre-installation checks are OK.

**Comment by topps** [comment]
Yes, the PHP version starts to create problems in OLab 3.4

OLab 3.3.1 is less fussy about that.

MySQL version does not seem to matter. MariaDB also works fine.

dt

From: Iraklis ***@***.***>
Reply-To: olab/Open-Labyrinth ***@***.***>
Date: Tuesday, April 6, 2021 at 07:00
To: olab/Open-Labyrinth ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [olab/Open-Labyrinth] Olab with php5.6 (#121)

[△EXTERNAL]


Hey there people! I'm working on a server that had olab3 installed years ago and after an attack, I'm trying to rebuild the whole thing. Unfortunately, my progress is slow, since the installation process is stopped after the app is trying to build the database. The server's OS is an Ubuntu 18.04, so it had php7 installed. I installed php5.6, as well, but the problem persists, just a blank screen after I fill the fields of the database name, etc. The app doesn't output any errors on the console and I can't seem to find any errors, so I'm guessing that olab3.4 is not compatible with php5.6? Maybe the version of MySQL is the problem (currently 5.7.33)? Can anyone confirm any of this or guide me through?

Thanks in advance!

P.S. All the pre-installation checks are OK.

**Comment by Iraklis** [comment]
Hey @topps sorry for the late response! You are right, 3.3.1 is playing along with php5.6, I successfully installed olab. At this point I'm finding a hard way to make it work with an already existing database, but this is another issue. Thanks a lot!
