### ISSUE TITLE
Can not import cases 

### ISSUE THREAD

**Issue by loxavia** [olab/Open-Labyrinth#88]
Server Centos PHP 5.5 OL v 3.3

Trying to import a labyrinth results in an error page like this

Error, labyrinth was not imported correctly. preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead
	
Whoops! Looks like something got lost in the Labyrinth.
A message has been sent to the technical team. They will look into this issue.
Please use the "back" arrow on your web browser to return to where you were before this happened.

**Comment by a-zharkov** [comment]
@sergey-rud Is this issue already fixed ?

**Comment by sergey-rud** [comment]
Fixed for cases when you installing/updating oLab. Not fixed during import.

**Comment by a-zharkov** [comment]
@sergey-rud Please fix it on import functionality.

**Comment by Mike19841984** [comment]
PHP 5.5.27, OLab 3.3.1, problem still there, would very much appreciate a fix.

**Comment by sergey-rud** [comment]
Fixed.

**Comment by Mike19841984** [comment]
Thanks. Is this included in the release candidate branch?

**Comment by topps** [comment]
Can you give us a bit more detail on what the problem is? Import of cases has not been dropped in any release, but depending on which version, is not universal across all releases in terms of what version can handle what.

What version are you exporting from? And what version are you importing into? And are you using the MVP format or the new Advanced format?

dt

From: Mike19841984
Reply-To: olab/Open-Labyrinth
Date: Sunday, September 27, 2015 at 2:44 AM
To: olab/Open-Labyrinth
Subject: Re: [Open-Labyrinth] Can not import cases (#88)


Thanks. Is this included in the release candidate branch?

**Comment by sergey-rud** [comment]
@Mike19841984 Yes, issue fixed in the release-candidate branch. Also you can correct this issue (that happens if your PHP version is 5.5.0 or newest) on your side, disable displaying "deprecated" errors on your server (in php.ini, using error_reporting directive).

But now it is not necessary for release candidate branch.
