### ISSUE TITLE
Generate a Labyrinth and display it outside the OpenLabyrinth

### ISSUE THREAD

**Issue by number-sense** [olab/Open-Labyrinth#96]
Hi again, 

I have already raised this issue with a previous question but didn't get an answer yet! 

I want to use the open labyrinth only as a tool to generate labyrinth use cases, which will be viewed by others privately as part of another website after they log in there! Is that possible? 

Regards

**Comment by d-semenyuk** [comment]
Hi, 
You can do it with import/export labyrinth. If you get message like "Oops ...". Please, press Ctrl + Q and send to us error message.

**Comment by number-sense** [comment]
Hi again, 

But both export options generate xml files only, whereas I need to display them outside the open labyrinth tool using a web browser in the same way it occurs in the tool it self, therefore I need some html and css files I guess that enables that! Is that possible?

**Comment by a-zharkov** [comment]
@number-sense Unfortunately, there is no such possibilities. During the playing of labyrinth the OpenLabyrinth send records to the database and run some php code in background and depending on user answer OLab move user in labyrinth in different ways. So that play labyrinth only like html is not possible.
